game: main.cpp game.cpp graphics.cpp input.cpp sprite.cpp animated_sprite.cpp player.cpp level.cpp tile.cpp tinyxml2.cpp animated_tile.cpp hud.cpp game.h graphics.h input.h sprite.h animated_sprite.h player.h level.h tile.h tinyxml2.h globals.h rectangle.h utils.h slope.h animated_tile.h hud.h door.h
	g++ main.cpp game.cpp graphics.cpp input.cpp sprite.cpp animated_sprite.cpp player.cpp level.cpp tile.cpp tinyxml2.cpp animated_tile.cpp hud.cpp -o game -lSDL2 -lSDL2_image

clean:
	rm game